In [54]:
import os

In [55]:
import pandas as pd
import numpy as np

Ques no.3

In [56]:
data={
  "Name" : ["Amit","Neha","Rahul","Sneha"],
  "Age" :[20, 21 , 19 , 22],
  "Marks": [85,90, 78,88] 
}

df=pd.DataFrame(data)          # pd.DataFrame()

df

    Name  Age  Marks
0   Amit   20     85
1   Neha   21     90
2  Rahul   19     78
3  Sneha   22     88

In [57]:
df.head(2)   #head()

   Name  Age  Marks
0  Amit   20     85
1  Neha   21     90

In [58]:
df[['Name','Marks']] #column selection

    Name  Marks
0   Amit     85
1   Neha     90
2  Rahul     78
3  Sneha     88

In [59]:
df["Result"]=['A','A+','B+','A']

In [60]:
df

    Name  Age  Marks Result
0   Amit   20     85      A
1   Neha   21     90     A+
2  Rahul   19     78     B+
3  Sneha   22     88      A

In [61]:
df[df["Marks"] > 80]  #column filtering

    Name  Age  Marks Result
0   Amit   20     85      A
1   Neha   21     90     A+
3  Sneha   22     88      A

ques 4

In [62]:
data={"Name" :["A","B", "C" ,"D"],
      "Age":[25 ,np.nan, 27, 24 ],
      "Salary": [30000, 40000, np.nan,35000] 
      }

df=pd.DataFrame(data)
df

  Name   Age   Salary
0    A  25.0  30000.0
1    B   NaN  40000.0
2    C  27.0      NaN
3    D  24.0  35000.0

In [63]:
df.isnull().sum()

Name      0
Age       1
Salary    1
dtype: int64

In [64]:
df["Age"] = df["Age"].fillna(df["Age"].mean())

In [65]:
df

  Name        Age   Salary
0    A  25.000000  30000.0
1    B  25.333333  40000.0
2    C  27.000000      NaN
3    D  24.000000  35000.0

In [67]:
df['Salary']=df['Salary'].fillna(df['Salary'].median())

In [68]:
df

  Name        Age   Salary
0    A  25.000000  30000.0
1    B  25.333333  40000.0
2    C  27.000000  35000.0
3    D  24.000000  35000.0

In [69]:
print("clean data:")
df

clean data:

  Name        Age   Salary
0    A  25.000000  30000.0
1    B  25.333333  40000.0
2    C  27.000000  35000.0
3    D  24.000000  35000.0

ques 5

In [70]:
df=pd.read_csv("Iris.csv")
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [ ]:
df.shape

(150, 6)

In [74]:
df["SepalLengthCm"].mean()

np.float64(5.843333333333334)

In [76]:
df["Species"].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [77]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

ques 2

Series:
1)One-dimensional data structure	
2)Contains a single column of data	
3)Similar to a list with index	
4)Created using pd.Series()

In [81]:
s= pd.Series([10, 20, 30, 40])
s

0    10
1    20
2    30
3    40
dtype: int64

*DataFrame:
1.Two-dimensional data structure
2.Contains multiple rows and columns
3.Similar to an Excel sheet or SQL table
4.Created using pd.DataFrame()*

In [84]:
data = {
    "Name": ["Amit", "Neha"],
    "Marks": [85, 90]
}

df = pd.DataFrame(data)
df

   Name  Marks
0  Amit     85
1  Neha     90

*loc[]:
Label (name) based indexing	
Uses row/column names	
End index is included	
Syntax: df.loc[row_label, column_label]	*

In [83]:
df.loc[1, "Name"]

'Neha'

iloc[]:
Integer position based indexing
Uses row/column numbers
End index is excluded in slicing
Syntax: df.iloc[row_index, column_index]

In [85]:
df.iloc[1, 0]

'Neha'

ques 1

Pandas is a Python library used to work with data in tables. It helps us read, organize, clean, and analyze data easily.

Role of Pandas in Data Analysis and Machine Learning
Loads data from CSV and Excel files.
Cleans data by removing errors and missing values.
Organizes data in rows and columns.
Analyzes data and calculates statistics.
Prepares data for machine learning models